---
bridge:
  backend: culqi
  public_key: "pk_test_POQJOT184VO1HOkc"
  private_key: "sk_test_69v3QXAnjKN00uqK"
delivery:
  smtp:
    host: "Your smtp endpoint"
    user: "<MAILJET_USERNAME>"
    password: "<MAILJET_PASSWORD>"
    from: "example@example.com"
  thermal:
    host: "Your thermal printer ip"
    passwordt: "Your secret"
