---
bridge:
  backends:
    - culqi:
        public_key: "..."
        private_key: "..."
    - paypal:
        public_key: "..."
        private_key: "..."
delivery:
  smtp:
    host: "Your smtp endpoint"
    user: "<MAILJET_USERNAME>"
    password: "<MAILJET_PASSWORD>"
    from: "example@example.com"
